In [1]:
import cv2
import numpy as np
import os
from glob import glob

In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers as L
from tensorflow.keras.callbacks import ModelCheckpoint, ReduceLROnPlateau, EarlyStopping, CSVLogger

In [11]:
global image_h
global image_w
global num_landmarks

""" Hyperparameters """
image_h = 512
image_w = 512
num_landmarks = 106
input_shape = (image_h, image_w, 3)
batch_size = 32

In [4]:
""" Paths """
path = "./LaPa"

In [13]:
train_img = sorted(glob(os.path.join(path, "train", "images", "*.jpg")))
train_land = sorted(glob(os.path.join(path, "train", "landmarks", "*.txt")))
valid_img = sorted(glob(os.path.join(path, "val", "images", "*.jpg")))
valid_land = sorted(glob(os.path.join(path, "val", "landmarks", "*.txt")))
test_img = sorted(glob(os.path.join(path, "test", "images", "*.jpg")))
test_land = sorted(glob(os.path.join(path, "test", "landmarks", "*.txt")))
train_img

['./LaPa\\train\\images\\10001436895_0.jpg',
 './LaPa\\train\\images\\10003645676_0.jpg',
 './LaPa\\train\\images\\10004446093_1.jpg',
 './LaPa\\train\\images\\10004446093_17.jpg',
 './LaPa\\train\\images\\10004446093_2.jpg',
 './LaPa\\train\\images\\10004446093_3.jpg',
 './LaPa\\train\\images\\10004446093_4.jpg',
 './LaPa\\train\\images\\10004446093_7.jpg',
 './LaPa\\train\\images\\10004446093_8.jpg',
 './LaPa\\train\\images\\10006787746_6.jpg',
 './LaPa\\train\\images\\10009875486_0.jpg',
 './LaPa\\train\\images\\10009875486_1.jpg',
 './LaPa\\train\\images\\10011648266_14.jpg',
 './LaPa\\train\\images\\100121306_0.jpg',
 './LaPa\\train\\images\\10012551673_0.jpg',
 './LaPa\\train\\images\\10012551673_1.jpg',
 './LaPa\\train\\images\\10012551673_10.jpg',
 './LaPa\\train\\images\\10012551673_11.jpg',
 './LaPa\\train\\images\\10012551673_13.jpg',
 './LaPa\\train\\images\\10012551673_6.jpg',
 './LaPa\\train\\images\\10012551673_7.jpg',
 './LaPa\\train\\images\\10012551673_9.jpg',
 './LaP

In [19]:
train_img = train_img.decode()

AttributeError: 'list' object has no attribute 'decode'

In [14]:
ds = tf.data.Dataset.from_tensor_slices((train_img, train_land))
for i in ds:
    print(i)
    print(i[0])
    print(i[1])
    print('-----------------------------------------------------------------------------------------') 

(<tf.Tensor: shape=(), dtype=string, numpy=b'./LaPa\\train\\images\\10001436895_0.jpg'>, <tf.Tensor: shape=(), dtype=string, numpy=b'./LaPa\\train\\landmarks\\10001436895_0.txt'>)
tf.Tensor(b'./LaPa\\train\\images\\10001436895_0.jpg', shape=(), dtype=string)
tf.Tensor(b'./LaPa\\train\\landmarks\\10001436895_0.txt', shape=(), dtype=string)
-----------------------------------------------------------------------------------------
(<tf.Tensor: shape=(), dtype=string, numpy=b'./LaPa\\train\\images\\10003645676_0.jpg'>, <tf.Tensor: shape=(), dtype=string, numpy=b'./LaPa\\train\\landmarks\\10003645676_0.txt'>)
tf.Tensor(b'./LaPa\\train\\images\\10003645676_0.jpg', shape=(), dtype=string)
tf.Tensor(b'./LaPa\\train\\landmarks\\10003645676_0.txt', shape=(), dtype=string)
-----------------------------------------------------------------------------------------
(<tf.Tensor: shape=(), dtype=string, numpy=b'./LaPa\\train\\images\\10004446093_1.jpg'>, <tf.Tensor: shape=(), dtype=string, numpy=b'./LaP

(<tf.Tensor: shape=(), dtype=string, numpy=b'./LaPa\\train\\images\\12361615355_0.jpg'>, <tf.Tensor: shape=(), dtype=string, numpy=b'./LaPa\\train\\landmarks\\12361615355_0.txt'>)
tf.Tensor(b'./LaPa\\train\\images\\12361615355_0.jpg', shape=(), dtype=string)
tf.Tensor(b'./LaPa\\train\\landmarks\\12361615355_0.txt', shape=(), dtype=string)
-----------------------------------------------------------------------------------------
(<tf.Tensor: shape=(), dtype=string, numpy=b'./LaPa\\train\\images\\12362843455_0.jpg'>, <tf.Tensor: shape=(), dtype=string, numpy=b'./LaPa\\train\\landmarks\\12362843455_0.txt'>)
tf.Tensor(b'./LaPa\\train\\images\\12362843455_0.jpg', shape=(), dtype=string)
tf.Tensor(b'./LaPa\\train\\landmarks\\12362843455_0.txt', shape=(), dtype=string)
-----------------------------------------------------------------------------------------
(<tf.Tensor: shape=(), dtype=string, numpy=b'./LaPa\\train\\images\\12362843455_1.jpg'>, <tf.Tensor: shape=(), dtype=string, numpy=b'./LaP

tf.Tensor(b'./LaPa\\train\\images\\198663742_0.jpg', shape=(), dtype=string)
tf.Tensor(b'./LaPa\\train\\landmarks\\198663742_0.txt', shape=(), dtype=string)
-----------------------------------------------------------------------------------------
(<tf.Tensor: shape=(), dtype=string, numpy=b'./LaPa\\train\\images\\1990106624_1.jpg'>, <tf.Tensor: shape=(), dtype=string, numpy=b'./LaPa\\train\\landmarks\\1990106624_1.txt'>)
tf.Tensor(b'./LaPa\\train\\images\\1990106624_1.jpg', shape=(), dtype=string)
tf.Tensor(b'./LaPa\\train\\landmarks\\1990106624_1.txt', shape=(), dtype=string)
-----------------------------------------------------------------------------------------
(<tf.Tensor: shape=(), dtype=string, numpy=b'./LaPa\\train\\images\\199092509_0.jpg'>, <tf.Tensor: shape=(), dtype=string, numpy=b'./LaPa\\train\\landmarks\\199092509_0.txt'>)
tf.Tensor(b'./LaPa\\train\\images\\199092509_0.jpg', shape=(), dtype=string)
tf.Tensor(b'./LaPa\\train\\landmarks\\199092509_0.txt', shape=(), dtype=s

(<tf.Tensor: shape=(), dtype=string, numpy=b'./LaPa\\train\\images\\2766788906_0.jpg'>, <tf.Tensor: shape=(), dtype=string, numpy=b'./LaPa\\train\\landmarks\\2766788906_0.txt'>)
tf.Tensor(b'./LaPa\\train\\images\\2766788906_0.jpg', shape=(), dtype=string)
tf.Tensor(b'./LaPa\\train\\landmarks\\2766788906_0.txt', shape=(), dtype=string)
-----------------------------------------------------------------------------------------
(<tf.Tensor: shape=(), dtype=string, numpy=b'./LaPa\\train\\images\\2766870255_0.jpg'>, <tf.Tensor: shape=(), dtype=string, numpy=b'./LaPa\\train\\landmarks\\2766870255_0.txt'>)
tf.Tensor(b'./LaPa\\train\\images\\2766870255_0.jpg', shape=(), dtype=string)
tf.Tensor(b'./LaPa\\train\\landmarks\\2766870255_0.txt', shape=(), dtype=string)
-----------------------------------------------------------------------------------------
(<tf.Tensor: shape=(), dtype=string, numpy=b'./LaPa\\train\\images\\2766870255_1.jpg'>, <tf.Tensor: shape=(), dtype=string, numpy=b'./LaPa\\train\

(<tf.Tensor: shape=(), dtype=string, numpy=b'./LaPa\\train\\images\\3604724725_4.jpg'>, <tf.Tensor: shape=(), dtype=string, numpy=b'./LaPa\\train\\landmarks\\3604724725_4.txt'>)
tf.Tensor(b'./LaPa\\train\\images\\3604724725_4.jpg', shape=(), dtype=string)
tf.Tensor(b'./LaPa\\train\\landmarks\\3604724725_4.txt', shape=(), dtype=string)
-----------------------------------------------------------------------------------------
(<tf.Tensor: shape=(), dtype=string, numpy=b'./LaPa\\train\\images\\3604724725_8.jpg'>, <tf.Tensor: shape=(), dtype=string, numpy=b'./LaPa\\train\\landmarks\\3604724725_8.txt'>)
tf.Tensor(b'./LaPa\\train\\images\\3604724725_8.jpg', shape=(), dtype=string)
tf.Tensor(b'./LaPa\\train\\landmarks\\3604724725_8.txt', shape=(), dtype=string)
-----------------------------------------------------------------------------------------
(<tf.Tensor: shape=(), dtype=string, numpy=b'./LaPa\\train\\images\\3604962221_1.jpg'>, <tf.Tensor: shape=(), dtype=string, numpy=b'./LaPa\\train\

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [18]:
""" Image """
image = cv2.imread(image_path, cv2.IMREAD_COLOR)
h, w, _ = image.shape
image = cv2.resize(image, (image_w, image_h))
image = image/255.0
image = image.astype(np.float32)

NameError: name 'image_path' is not defined

In [6]:
def preprocess(x, y):
    def f(x, y):
        x = x.decode()
        y = y.decode()

        image, landmarks = read_image_lankmarks(x, y)
        return image, landmarks

    image, landmarks = tf.numpy_function(f, [x, y], [tf.float32, tf.float32])
    image.set_shape([image_h, image_w, 3])
    landmarks.set_shape([num_landmarks * 2])

    return image, landmarks

In [16]:
def tf_dataset(x, y):
    ds = tf.data.Dataset.from_tensor_slices((x, y))
    ds = ds.shuffle(buffer_size=5000).map(preprocess)
    ds = ds.batch(batch).prefetch(2)
    return ds

In [20]:
train_ds = tf_dataset(train_img, train_land, batch=batch_size)
valid_ds = tf_dataset(valid_img, valid_land, batch=batch_size)

In [23]:
ds_train = tf.data.Dataset.from_tensor_slices((train_img, train_land))
ds_valid = tf.data.Dataset.from_tensor_slices((valid_img, valid_land))

In [25]:
ds_train = ds_train.shuffle(buffer_size=5000)

In [26]:
# ds_train = ds_train.decode()
# https://velog.io/@mmzgpgp/AttributeError-str-object-has-no-attribute-decode-%EC%97%90%EB%9F%AC

# 파이썬에서 AttributeError: 'str' object has no attribute 'decode' 이런 메시지가 뜨시면
# 해당 코드 줄의 .decode() 부분을 지우시면 됩니다.
# 이미 decode가 되었기 때문에 decode할게 없다는 뜻 입니다.

AttributeError: '_ShuffleDataset' object has no attribute 'decode'

In [27]:
image = cv2.imread(ds_train, cv2.IMREAD_COLOR)

TypeError: Can't convert object to 'str' for 'filename'